### ISSUE TITLE
It's for MacOS, right? Is it built on Metal API?

### ISSUE THREAD

**Issue by shakatoday** [byulparan/cl-visual#2]
It's for MacOS, right? Is it built on Metal API? 
OpenGL is deprecated by Apple Inc. even though currently still presents.
I'm just afraid any OpenGL-based softwares stops working on Mac in some future.

**Comment by byulparan** [comment]
It's run on OpenGL, so I affraid too🥶. But I think OpenGL will long live in macOS(like now).
If OpenGL complete remove in macOS, I will find alternate new thing(Vulkan, Metal, MoltenGL etc).

in fact I am not very concerned. cl-visual is just small library.
